---
- name: Fetching required Ansible Roles
  hosts: localhost
  become: false
  connection: local
  gather_facts: false
  tasks:
    - name: Install Ansible Roles
      local_action:
        module: shell
        cmd: ansible-galaxy install -r requirements.yml

- name: Applying Ansible Playbook
  hosts: all
  become: false
  gather_facts: true
  pre_tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
  tasks:
    - name: Execute Jupyter Notebook Install Process
      include_role:
        name: jupyter-notebook
