---
- name: Fetching required Ansible Roles
  hosts: localhost
  become: false
  connection: local
  gather_facts: false
  tasks:
    - name: Install Ansible Roles
      local_action:
        module: shell
        cmd: ansible-galaxy install -r requirements.yml

- name: Applying Ansible Playbook
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: false
  gather_facts: true
  pre_tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Install Python 3 on Debian
      apt:
        name:
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"
  tasks:
    - name: Execute Jupyter Notebook Install Process
      include_role:
        name: jupyter-notebook
