---
- hosts: all
  become: true
  gather_facts: true
  vars:
    build_docker_image: "{{ lookup('env', 'BUILD_DOCKER_IMAGE') | default('F', true) }}"
  pre_tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Install Ansible Roles
      local_action:
        module: shell
        cmd: ansible-galaxy install -r requirements.yml
  tasks:
    - name: Execute Jupyter Notebook Install Process
      include_role:
        name: notebook